# Numpy

* Numpy is used to do scientific computation (MEANS to do more advance mathematical computation)
* https://numpy.org/
* written in c hence fast 
* used basically for machine learning and computation
* pytorch is for deeplearning 
* you can use your gpu well with pytorch 
* numpy is faster also because it is optimized 
* ML is possible with python also but if we have to do lot more calculations 
* In python we only have int,long or float , double 
* while in ML we need even more precision sometimes till 0.00000000000000000000000000000000001 so we use numpy which gives us more precision 
* we will have lot more datatypes like int, int16, int 32, int 84 also float 16, 32 etc
* Libraries like pandas and ML libraries like scikit learn has numpy enternally 
* operations performed here are vectorized , memory efficient. can also do linear algebra here           

In [1]:
# !pip install numpy
#  but no need to install because it comes bydefault with your base package

In [2]:
import numpy as np
import time

In [15]:
a = list(range(100000000))
b = list(range(100000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
end_t = time.time()
time_taken_p = end_t-start_t
print(f"Time taken : {time_taken_p}")

Time taken : 3.774937868118286


In [17]:

a = list(range(100000000))
b = list(range(100000000))
a = np.array(a)
b = np.array(b)

start_t = time.time()
c = a + b
end_t = time.time()
time_taken_n = end_t-start_t
print(f"Time taken : {time_taken_n}")

Time taken : 0.6903369426727295


In [ ]:
#  Here we can see that Time taken by numpy version is less than time taken by python 

In [19]:
time_taken_p/time_taken_n


# here  numpy is 5.468254173828684 folds faster 


5.468254173828684

# 1. np.array()

In [ ]:
#  array is more strict we cannot have multiple data types , just have one datatype (homogenous data not hetrogenes)
# also we have n-dimentional array (multi-dimentional)

In [22]:
array_n1 = np.array([1,2,3])

In [23]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0])) # type of value stored in array int64

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [160]:
array_n2 = np.array([1,2,3], dtype=np.int8)
print(type(array_n2))
print(type(array_n2[0]))

<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [162]:
array_n2 = np.array([1,2,"3"], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [24]:
array_n2 = np.array([1,2,"3"], dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

# dot means float value 

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2. np.arange(start, stop, step)

In [28]:
print(np.arange(5))

print(np.arange(1, 10, 2))

np_arange = np.arange(1, 10, 2)
print(type(np_arange))
print(type(list(np_arange)))

[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>
<class 'list'>


# np.linspace(start, stop, num=x)

In [32]:
np_linspace = np.linspace(1,100,4)
# (1,100,4) means equally spaced 4 numbers from 1 to hundred 
# (1,2,10) means equally spaced 10 numbers from 1 to 2 

print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [30]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [33]:
npz_1 = np.zeros(5)
# create array of values filled with zeros

In [ ]:
#  For ML and DL , for model training and AI training  we always use float, later when the model is ready then we convert it to integer thats why float is by default 

In [34]:
npz_1

array([0., 0., 0., 0., 0.])

In [ ]:
#  For 1 dimention 
[]
# For 2 dimention 
[[],[]]
# For 3 dimention 
[[[],[]],[[],[]]]

In [ ]:
#  To make multiple one D we have to make a 2D list 
[[],[],[]]
#  To contain multiple of 2D i have to create another dimention  
[[[],[],[]],[[],[],[]],[[],[],[]]]

In [35]:
npz_1.ndim

1

In [41]:
npz_2 = np.zeros((5,5))
# 5 rows and 5 coloumns
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [186]:
npz_2.ndim

2

In [ ]:
npz_3 = np.zeros((5,5,5))
#  i want 5 times an array of size 5 * 5
#  i want 2D matrix of size 5*5. i want 5 of them 
# like  5*5 ,  5*5,  5*5,  5*5,  5*5
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [43]:
npz_3.ndim

3

In [ ]:
# As a human we live in a 3d world but we cannot watch ourselved so we cannot see 3D

In [44]:
npz_4 = np.zeros((5,5,5,5))

In [45]:
npz_4

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [ ]:
a11 = [[[]],[[],[]]]

a11 = np.array(a11)

a11

# ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.