# numpy math operations

##### Vector is a 1D array

##### Matrix is a 2D array

##### If multiple dimentions then we call it as n dimention array 


In [54]:
#  Everything is vectorize we don't need to use any for loop here 

In [1]:
a = [1,2,3]
b = [4,5,6]

a + b  # vectorized operation

[1, 2, 3, 4, 5, 6]

In [6]:
import numpy as np

In [8]:
print([1,2,3,4])
print(np.array([1,2,3,4]))

[1, 2, 3, 4]
[1 2 3 4]


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
print(type(a + b))

<class 'numpy.ndarray'>


In [12]:
print(a + b)

[5 7 9]


In [13]:
print(a-b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [14]:
# comparison
#  It is element by element
print(a > b)
print(a < b)
print(a == b)

[False False False]
[ True  True  True]
[False False False]


In [15]:
ans = a > b
print(type(ans[0]))

<class 'numpy.bool'>


In [20]:
# logical operators

# and , or , not

x = np.array([True, False, True])
y = np.array([False, False, True])

print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


In [15]:
# bitwise operators

a = np.array([1, 2, 3])
b = np.array([0, 1, 1])

# e.g.
#  if i convert 2 to bit and 1 to bit then do and operator then i can get zero 

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))

[0 0 1]
[1 3 3]


In [16]:
# modulus and power

a = np.array([10, 20, 30])
b = np.array([3, 7, 4])

# e.g.
# If we divide 10/3 what is the reminder that we will get = 1

print(np.mod(a, b))
print(np.power(a, b))


[1 6 2]
[      1000 1280000000     810000]


# scalar opertions

In [18]:
celcius = np.array([0, 10, 20, 30])
# to_farenheit = np.array([33.8, 33.8, 33.8, 33.8]) # broadcasting
print(celcius * (9 / 5 + 32))

# multiplication of scalat value with vector is managed by numpy and is called broadcasting 

[   0.  338.  676. 1014.]


In [20]:
# in python
celsius = [0, 10, 20, 30]
fahrenheit = celsius * (9 / 5 + 32)
print(fahrenheit)

#  IN normal python this cannot be done 

TypeError: can't multiply sequence by non-int of type 'float'

# Common maths functions

In [22]:
a = np.array([1, 2, 3, 4])

print(np.sqrt(a))  # squareroot of each and every element 
print(np.exp(a)) # e^1, e^2, where e = 2.718, pi = 3.14
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [23]:
#  you want to know where the e is used 
# machine learning
# activation function

# sigmoid


x = np.array([-1, 0, 1])
sigmoid = 1 / (1 + np.exp(-x))
print(sigmoid)

[0.26894142 0.5        0.73105858]


In [ ]:
# Aggregation functions

#  Summarization of numbers

In [40]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [44]:
print(np.sum(a))

21


In [ ]:
print(np.sum(a, axis=0))
# across all rows, fix the column

[5 7 9]


In [45]:
print(np.sum(a))
print(np.mean(a)) # average
print(np.std(a))
print(np.min(a))
print(np.max(a))

21
3.5
1.707825127659933
1
6


# matrix operation

In [ ]:
# element-wise multiplication

In [27]:
units_sold = np.array([100, 200, 150])
profit = np.array([10, 20, 30])

#  as i wanat to see profit in each item sold 

In [ ]:
|units_sold * profit

array([1000, 4000, 4500])

# Matrix multiplication 
## Dot product (explaination notes)
* col of 1st matrix must be equal to row of second metrix for multiplication 
* and the result will be row of 1st matrix * col of second metrix


In [55]:
# sqft
# bedroom
# location 1 G, 0 B

In [ ]:
house = np.array([1200, 3, 1]) # This is the data we get from the client 
w = np.array([200, 10000, 50000]) # This is how our machine learning data looks like 

In [52]:
#  As it is a 1D matrix you don't need a transpose 
# For 2 D and others you don't need a transpose 
print(np.dot(house, w))

# By this i will get the price of the house 

320000


In [43]:
house = np.array([[1200, 3, 1],
                  [1200, 3, 0],
                  [1000, 3, 0],
                  [1000, 1, 1]])

In [44]:
w = np.array([200, 10000, 50000])

In [37]:
print(house.shape)
print(w.shape)

(4, 3)
(3,)


In [53]:
print(np.dot(house, w))
#  We are getting all the prices of the house 

#  in dot product here we can see that it do the multiplication + adding all as well

320000


In [49]:
house = np.array([[1200, 3, 1],
                  [1200, 3, 0],
                  [1000, 3, 0],
                  [1000, 1, 1]])

w = np.array([200, 10000, 50000])

mul = house * w
print(mul)

[[240000  30000  50000]
 [240000  30000      0]
 [200000  30000      0]
 [200000  10000  50000]]


In [ ]:
print(np.sum(mul , axis=1)) # multiplication + sum
#  Hence dot ptoduct is nothing but multiplication and sum across column 



[320000 270000 230000 260000]


In [29]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [30]:
print(A.shape)
print(B.shape)

(2, 4)
(2, 4)


In [31]:
print(np.dot(A, B))

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [32]:
print(np.dot(A, B.T))

[[30 30]
 [30 30]]


In [ ]:
# Another way of doing dot product is @ 
print(A @ B.T)

[[30 30]
 [30 30]]


# broadcasting

In [ ]:
a = np.array([1, 2, 3]) # (3,)
b = np.array([[10], [20]]) # (2,1)

#  Because the shape is different we cannot add directly 

#  because of broadcasting we can do that

In [104]:
print(a.shape)
print(b.shape)

(3,)
(2, 1)


In [ ]:
a + b

# a (1,3)--> make it something like this (2,3) => [[1, 2, 3], [1, 2, 3]]
# b (2,1)--> make it something like this (2,3) => [[10, 10, 10], [20, 20, 20]]

array([[11, 12, 13],
       [21, 22, 23]])

# creating arrays from exisiting data

In [114]:
a = [1,2,3,4]
b = ([[1,2], [2,3]])
c = (10,20,30)

In [115]:
a_npy = np.array(a)
print(a_npy, a_npy.dtype, type(a))

[1 2 3 4] int64 <class 'list'>


In [116]:
b_npy = np.array(b)
print(b_npy, b_npy.dtype, type(b))

[[1 2]
 [2 3]] int64 <class 'list'>


In [117]:
c_npy = np.array(c)
print(c_npy, c_npy.dtype, type(c))

[10 20 30] int64 <class 'tuple'>


In [118]:
# vstack

a = np.array([[1,2]])
b = np.array([[3,4]])

In [ ]:
print(np.vstack((a,b)))
#  I want to stack a on top of b to get the new array  

[[1 2]
 [3 4]]


In [120]:
print(np.hstack((a,b)))

[[1 2 3 4]]


In [ ]:
#  To work with string operations we use np.char. In this we have all the functions to work with chracters 

# np.char.<function_name>()

# 1. np.add()

# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [123]:
# np.char.multiply()

print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [60]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [62]:
# np.char.center()

print(np.char.center(a, 10, fillchar='*'))

#  maximum i want is 10 chracters 
#  Fill by *

['**hello***' '**WORLD***']


In [129]:
a = np.array(['data_science', 'machine_learning'])

In [130]:
# np.char.replace()

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [131]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
# np.char.find() / np.char.count()

print(np.char.find(a, 'learn')) 
#  [-1  8] => -1 means i am unable to find learn in the first value. 
print(np.char.count(a, 'a'))
#  want to count the total no of a present in each word 
print(np.char.count(a, 'data'))

[-1  8]
[2 2]
[1 0]


# statistical functions

In [135]:
data = np.array([1, 2, 3, 4, 5, 6])

In [139]:
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Min: 1
Max: 6


In [ ]:
#  Help us find the undex of min and max value 
print("Argmin:", np.argmin(data))
print("Argmax:", np.argmax(data))

Argmin: 0
Argmax: 5


In [63]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(np.mean(matrix, axis=0)) # Mean with the axis 0
print(np.mean(matrix, axis=1))  # Mean with the axis 1

[2.5 3.5 4.5]
[2. 5.]


In [64]:
# Percentile

# total 9000 people appeared in exam 

#  i got 50%

#  6000 people scored less than me 

#  my  percentile is  (6000 / 9000 ) * 100

# 66.66% is my percentile 

#  A percentile of 66.66% means that you scored higher than 66.66% of the people who took the exam.

In [65]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50)) # range 1 - 100
# 50 is percentile here and below 5 every thing comes in 50  percentile 
print(np.quantile(data, 0.5)) # nothing but percentile but expressed between  range 0 - 1
print(np.quantile(data, 1))

5.0
5.0
9


# sort, search, counting functions

In [ ]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr)) # Index of the sorted version 
#    i want to insert 4 in the sorted array which index i will be inserting 
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4)) # Help us where we can insert 4 in the sorted array 
print("Unique elements:", np.unique(arr))


# ************************************************************************
print("Count of each element:", np.bincount(arr))

#  Explaination given below 
# min - 1
# max - 8
# creates an array from 0 to max element (8)
# 0, 1, 2, 3, 4, 5, 6, 7, 8 --> len(9)
#  and then tells the no of time each appear in arr 

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]
Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [158]:
arr = np.array([1, 2, 3, 4])

for x in arr:
    print(x)

1
2
3
4


In [159]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [67]:
(2,2,2)

a = np.array([[[1 , 2],[ 3, 4]],[[ 5, 6],[7 ,8 ]]])

a.shape



(2, 2, 2)

In [70]:
arr = np.arange(8).reshape(2,2,2)

for x in arr:
    print(x)

#  It is just printing 
# [[0 1]
#  [2 3]]
#  in first iteration  and 
# [[4 5]
#  [6 7]]
#  and this is second iteration 


[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
arr = np.arange(8).reshape(2,2,2)
# if want to iterate over all elements without getting into the dimentions 
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [171]:
a = np.array([1, 2, 3])

In [172]:
b = a

In [173]:
print(id(a))
print(id(b))

2182904262896
2182904262896


In [174]:
b[0] = 100

In [175]:
print(a)

[100   2   3]


In [179]:
a = np.array([1, 2, 3])

In [71]:
b = a.copy()
#  now a new memory allocation will happen with the same memory elements and now they will be present in b 
#  Here a new reference will be allotted 

In [181]:
print(id(a))
print(id(b))

2182904263280
2182904045296


In [182]:
b[0] = 100

In [183]:
print(a)

[1 2 3]


In [184]:
a = np.array([1, 2, 3])

b = a.view()

c = a.copy()

In [185]:
b[0] = 10
print(a)

[10  2  3]


In [186]:
c[0] = 20
print(a)

[10  2  3]


In [72]:
a = np.arange(5)
b = a[1:4] # view
print(np.shares_memory(a, b))

True


In [74]:
print(id(a))
print(id(b))

4411096208
4833670704


In [188]:
a = np.arange(5)
b = a[1:4].copy()
print(np.shares_memory(a, b))

False


In [81]:
a = np.array([[1, 2], [3, 4]])
print(a.ravel()) # Like a view 
print(a.flatten())

[1 2 3 4]
[1 2 3 4]


In [79]:
a = np.array([[1, 2], [3, 4]])
b = a.ravel()
print(id(a) == id(b))
print(np.shares_memory(a, b))

False
True


In [80]:
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
print(id(a) == id(b))
print(np.shares_memory(a, b))

False
False




---

# **🔹 Task 1**

```python
import numpy as np
a = np.array([1, 2, 3])

b = a 
c = a.view()
d = a.copy()
```

### 1. `b = a`

* **Memory:** `b` is just another **reference** (pointer) to the *same* NumPy array object `a`.
* Both `a` and `b` share:

  * Same **data buffer** (the actual numbers in memory).
  * Same **array object metadata** (shape, dtype, strides).
* If you change `b[0]`, `a[0]` also changes, because they are literally the same object.
* `id(a) == id(b)` ✅

---

### 2. `c = a.view()`

* **Memory:** `c` is a **new NumPy array object**, but it **shares the same data buffer** with `a`.
* Metadata (shape, dtype, strides) is new, but the underlying data memory is the same.
* Example:

  ```python
  c[0] = 99
  print(a)  # [99  2  3]
  ```
* BUT: if you reshape or slice `c`, only the *view* changes, data stays shared.
* `id(a) != id(c)` (different objects), but `c.base is a` ✅ (they share memory).

---

### 3. `d = a.copy()`

* **Memory:** `d` is a completely **new NumPy array object** with its **own independent data buffer**.
* No sharing at all.
* Changing `d` does not affect `a`:

  ```python
  d[0] = 42
  print(a)  # [1 2 3]
  print(d)  # [42 2 3]
  ```
* `id(a) != id(d)` and also `d.base is None` ✅

---

### **Memory diagram for Task 1**

```
Array objects (metadata like shape, dtype, strides):
a ─┐
b ─┘ ──────────────> [ 1, 2, 3 ]  (shared data buffer)
c ────────────────> [ 1, 2, 3 ]  (same data buffer, different view object)
d ────────────────> [ 1, 2, 3 ]  (independent copy, new buffer)
```

---

# **🔹 Task 2**

```python
a = np.arange(5)      # [0, 1, 2, 3, 4]
b = a[1:4]            # view (slice)
c = a[1:4].copy()     # copy
```

### 1. `b = a[1:4]`

* Slicing creates a **view**.
* `b` points to the **same data buffer as `a`**, just with different metadata (start index, strides, length).
* Memory not duplicated.
* If you change `b[0]`, it changes `a[1]`.

---

### 2. `c = a[1:4].copy()`

* Creates a **completely new data buffer** with values `[1, 2, 3]`.
* Independent of `a`.
* If you change `c[0]`, nothing happens in `a`.

---

### **Memory diagram for Task 2**

```
a ───────────────> [ 0, 1, 2, 3, 4 ]  (data buffer)

b ───────────────> (view: starts at index 1, length 3, strides)
                      points to same buffer region [1, 2, 3]

c ───────────────> [ 1, 2, 3 ]  (independent copy, new buffer)
```

---

# **🔹 Task 3**

```python
a = np.array([[1, 2], [3, 4]])
print(a.ravel())
print(a.flatten())
```

### 1. `a.ravel()`

* Returns a **flattened 1D view if possible**.
* If the array is contiguous in memory (which it usually is for simple arrays), `ravel()` will **share the same data buffer**.
* If you modify the result of `ravel()`, the original `a` may change (when possible).

---

### 2. `a.flatten()`

* Always returns a **new copy** of the array as a 1D array.
* Independent buffer, no memory sharing.
* Changes to `flatten()` output do not affect `a`.

---

### **Memory diagram for Task 3**

```
a ───────────────> [[1, 2],
                     [3, 4]]  (contiguous memory)

a.ravel() ───────> [1, 2, 3, 4] (view, shared buffer if contiguous)
a.flatten() ─────> [1, 2, 3, 4] (independent copy, new buffer)
```

---

# **📝 Summary at Memory Level**

| Operation          | New Object?  | Shares Data Buffer? | Independent Copy? |
| ------------------ | ------------ | ------------------- | ----------------- |
| `b = a`            | ❌ (same obj) | ✅ (same buffer)     | ❌                 |
| `a.view()`         | ✅            | ✅                   | ❌                 |
| `a.copy()`         | ✅            | ❌                   | ✅                 |
| Slice `a[1:4]`     | ✅ (view)     | ✅                   | ❌                 |
| `.copy()` on slice | ✅            | ❌                   | ✅                 |
| `.ravel()`         | ✅            | ✅ if contiguous     | ❌                 |
| `.flatten()`       | ✅            | ❌                   | ✅                 |

---

